version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - tox-env-{{ checksum "requirements2.txt" }}-{{ checksum "requirements3.txt" }}
            # fallback to using the latest cache if no exact match is found
            - tox-env-
          paths: 
            - .tox
      - run:
          name: install python header for building scandir
          command: |
            sudo apt-get install python-dev
      - run:
          name: install tox 
          command: |
            python3 -m venv ../venv
            . ../venv/bin/activate
            pip install tox

      - save_cache:
          paths:
            - .tox
          key: tox-env-{{ checksum "requirements2.txt" }}-{{ checksum "requirements3.txt" }}
        
      - run:
          name: run tests
          command: |
            . ../venv/bin/activate
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
